# https://docs.aws.amazon.com/ja_jp/codebuild/latest/userguide/build-env-ref-env-vars.html
version: 0.2

env:
  variables:
    DOCKER_BUILDKIT: "1"
    AWS_DEFAULT_REGION: "ap-northeast-1"
    REPOSITORY_NAME: "ecr-app-api"
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - ECR_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${REPOSITORY_NAME}
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
  build:
    commands:
      - ./gradlew :api:bootBuildImage --imageName=${ECR_URI}:${IMAGE_TAG}
      - docker push ${ECR_URI}:${IMAGE_TAG}
  post_build:
    commands:
      - bash taskdef.sh -p ${ACTIVE_PROFILE} -a ${AWS_ACCOUNT_ID}
      - printf '{"ImageURI":"%s"}' ${ECR_URI}:${IMAGE_TAG} > imageDetail.json
artifacts:
  files:
    - appspec.yaml
    - taskdef.json
    - imageDetail.json
